name: rentara_property_clone
description: "Rentara Property App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
#  flutter_hooks: ^0.21.3+1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  go_router: ^17.0.1
  google_maps_flutter: ^2.14.0
  google_maps_cluster_manager_2: ^3.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  injectable: ^2.7.1+4
  google_fonts: ^7.0.0
  freezed_annotation: ^3.1.0
  permission_handler: ^12.0.1
  collection: ^1.19.1
  gradient_borders: ^1.0.2
  flutter_native_splash: ^2.4.7
  flutter_bounceable: ^1.2.0
  fluttertoast: ^9.0.0
  email_validator: ^3.0.0
  lottie: ^3.3.2
  device_info_plus: ^12.3.0
  geolocator: ^14.0.2
#  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  json_serializable: ^6.11.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rentara_logo_img.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animation/
    - config/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
